### ISSUE TITLE
[Android] Subscription's price in wrong format. 

### ISSUE THREAD

**Issue by jaroslawkrol** [apphud/ApphudSDK-React-Native#4]
Hello, 

There is something wrong, with format of data returned by ApphudSDK for Android. 

In `src/index.ts`, you declared price of ApphudProduct interface as number: 

```
export interface ApphudProduct {
  id: string;
  price: number; // <!-- price declared as number
  regionCode: string;
  currencyCode?: string;
}
``` 

but SDK returns string in this attribute:

![image](https://user-images.githubusercontent.com/10097549/110131212-36221080-7dca-11eb-95d2-31c5bc4c71e3.png)

**Comment by alexandr-makarov-am** [comment]
Thank you for the feedback. This issue fixed in 1.0.3 version.
