### ISSUE TITLE
Data migration support ?

### ISSUE THREAD

**Issue by Artem2001S** [apphud/ApphudSDK-React-Native#44]
My application uses Adapty purchases SDK. I want to migrate to Apphud

There is no information about react native in data migration guide ([https://docs.apphud.com/getting-started/data-migration-guide](https://docs.apphud.com/getting-started/data-migration-guide)) 

Is React Native SDK support data migration ?

**Comment by ren6** [comment]
Hello! Yes, you should have just call restorePurchases or syncPurchases method. I hope you migrated well!
