### ISSUE TITLE
[Android] Wrong subscription details 

### ISSUE THREAD

**Issue by jaroslawkrol** [apphud/ApphudSDK-React-Native#5]
I can't fetch correct data about user current subscription. 

`.subscription()` method should return last subscription status, but when i try to call it I get old data. 

I just ordered subscription, and after that I got: 

![image](https://user-images.githubusercontent.com/10097549/110135696-1c36fc80-7dcf-11eb-86e2-d598f2354fca.png)

but when I try to buy the same subscription again, Android dialog tells me that I have already this one. 

This issue don't allow to show information about current subscription.

**Comment by alexandr-makarov-am** [comment]
I need to look at the you code to answer this issue. @jaroslawkrol

**Comment by jaroslawkrol** [comment]
@alexandr-makarov-am 

```
public static async init(uid: string) {
    await this.setupPurchases(uid);
    this.fetchSubscriptionInfo();
}

private static async setupPurchases(uid: string) {
    await ApphudSdk.start({
      apiKey: 'app_xxx',
      deviceId: getDeviceId(),
      userId: uid,
    });
}  

private static async fetchSubscriptionInfo() {
    try {
      const subscriptionInfo = await ApphudSdk.subscription();
      Store.dispatch(setSubscriptionInfo(subscriptionInfo));
    } catch (e) {
      Store.dispatch(setSubscriptionInfo(null));
    }
  }
  ```

**Comment by ren6** [comment]
@jaroslawkrol hi! Sorry for late response. Do you still have this issue?
Subscription info is cached on device, and after each app launch it is being refreshed.
If you got old subscription info, it means that android purchase wasn't send to our servers.
Are you purchasing subscription using your own method or using Apphud methods?
please share the code of purchasing subscription

**Comment by ren6** [comment]
@jaroslawkrol Hi again! Sorry for late reply. Our React Native SDK has been updated. A bug with subscription expiration time zone date was fixed. Luckily, it affected only test subscriptions. Please update, and if you have any issues, we appreciate to contact us via online chat (Intercom). We answer much quickly there (0-1 business days).
