### ISSUE TITLE
[Android] Crash app after starting SDK 

### ISSUE THREAD

**Issue by jaroslawkrol** [apphud/ApphudSDK-React-Native#6]
in `src/index.ts` parameter `deviceId` is presented as optional: 

```
export interface StartProperties {
  apiKey: string;
  userId?: string;
  deviceId?: string;
  observerMode?: boolean;
}
```

but starting Apphud in this way: 

```
ApphudSdk.start({
   apiKey: 'api_xxx',
   userId: 'uuid007'
});
```
cause a crash of app with totally unclear message `deviceId`.

**Comment by alexandr-makarov-am** [comment]
This issue fixed in v1.0.3. After updating you need reinstall app, because deviceId is saved in shared preferences.
